### ISSUE TITLE
Exception: Reading transport stream, but object is disposed

### ISSUE THREAD

**Issue by Moonbird-IT** [unosquare/embedio#118]
We recently updated from product version 1.6.9 to version 1.11.3 and now we constantly get the following message in our application's log file:
```
Unosquare.Net.HttpConnection+<BeginReadRequest>d__37.MoveNext - FirstChanceException event raised in xyz.Main.exe System.IO.IOException: Unable to read data from the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
```
On the web client's side we can only see that sometimes requests take long to be handled but this doesn't necessarily be due to misbehaving of EmbedIO.

**Comment by geoperez** [comment]
Hi @Moonbird-IT , what target framework are you using?

**Comment by Moonbird-IT** [comment]
We are currently on .NET-Framework 4.6.2.

**Comment by geoperez** [comment]
Can you provide a code snippet? Like what EmbedIO modules are you using?

**Comment by Moonbird-IT** [comment]
We are using the WebAPI, here's part of our web server handler:

`public class WebServerHandler 
{
	// ...
	
	public bool Initialize(string url)
	{
		#region parameter checks
		
		if (url == null)
		{
			throw new ArgumentNullException(nameof(url));
		}
		
		if (string.IsNullOrEmpty(url))
		{
			throw new ArgumentException($"'{nameof(url)}' must not be empty.");
		}
		
		#endregion parameter checks

        var initializationSuccess = true;
        var manualResetEvent = new ManualResetEvent(false);
			
        Terminal.OnLogMessageReceived += this.OnEmbedIoLogMessageReceived;
        Terminal.Settings.DisplayLoggingMessageType = LogMessageType.None;

        this.server = new WebServer(url);
        this.server.RegisterModule(new WebApiModule());
        this.server.Module<WebApiModule>().RegisterController(() => this.factory.Create());
        this.cancellationTokenSource = new CancellationTokenSource();

        this.webServerTask = this.server.RunAsync(this.cancellationTokenSource.Token);
        this.webServerTask.ContinueWith(t =>
			{
				initializationSuccess = false;
				ApplicationLogger.Log.Error($"An exception occured during initialization of the {nameof(WebServerHandler)}.", t.Exception);
				manualResetEvent.Set();
			}, TaskContinuationOptions.OnlyOnFaulted);

		
		manualResetEvent.WaitOne(500);

        if (initializationSuccess)
        {
			ApplicationLogger.Log.Debug($"Initialization of {nameof(WebServerHandler)} succeeded.");
        }

        this.shutdown = false;

        return initializationSuccess;
	}
}
		
		
public class DataboxApiController : WebApiController
{
	// ...
		
	[WebApiHandler(HttpVerbs.Get, "/*")]
    public bool Handle(WebServer server, Unosquare.Net.HttpListenerContext context)
	{
		#region parameter check
		
		if (server == null)
		{
			throw new ArgumentNullException(nameof(server));
		}
		
		if (context == null)
		{
			throw new ArgumentNullException(nameof(context));
		}
		
		#endregion parameter check
		
		ApplicationLogger.Log.Debug($"Handling request '{context.Request.Url}' " +
									$"from remote endpoint '{context.Request.RemoteEndPoint}'.");
									
		string decodedRequest = HttpUtility.UrlDecode(context.Request.RawUrl);
		string handleResult = this.webrequestDispatcher.Handle(decodedRequest);
		
		context.Response.AddHeader("Access-Control-Allow-Origin", "*");
		return context.JsonResponse(handleResult);
	}
}`

**Comment by mariodivece** [comment]
I can't reproduce the issue. I am using the following sample code (Console application dotnetcore 2.0)
Could you let us know your build details? Framework version, Visual studio, etc?

```csharp
using System;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using Unosquare.Labs.EmbedIO;
using Unosquare.Labs.EmbedIO.Constants;
using Unosquare.Labs.EmbedIO.Modules;
using Unosquare.Swan;

namespace EmbedIO.Samples.WebApi01
{
    class Program
    {
        static WebServer server = null;
        static Task webServerTask = null;
        static CancellationTokenSource cancellationTokenSource;

        static void Main(string[] args)
        {
            InitializeWebServer("http://localhost:9696");
            Console.ReadLine();
        }

        private static bool InitializeWebServer(string url)
        {
            #region parameter checks

            if (url == null)
            {
                throw new ArgumentNullException(nameof(url));
            }

            if (string.IsNullOrEmpty(url))
            {
                throw new ArgumentException($"'{nameof(url)}' must not be empty.");
            }

            #endregion parameter checks

            var initializationSuccess = true;
            var manualResetEvent = new ManualResetEvent(false);

            Terminal.OnLogMessageReceived += (s, e) => { Console.WriteLine(e.Message); /* Replace with your custom application logger */ };
            Terminal.Settings.DisplayLoggingMessageType = LogMessageType.None;

            server = new WebServer(url);
            server.RegisterModule(new WebApiModule());
            server.Module<WebApiModule>().RegisterController(() => new DataboxApiController());
            cancellationTokenSource = new CancellationTokenSource();

            webServerTask = server.RunAsync(cancellationTokenSource.Token);
            webServerTask.ContinueWith(t =>
            {
                initializationSuccess = false;
                t.Exception.ExceptionMessage().Error();
                manualResetEvent.Set();
            }, TaskContinuationOptions.OnlyOnFaulted);


            manualResetEvent.WaitOne(500);

            if (initializationSuccess)
            {
                $"Initialization of {nameof(WebServer)} succeeded.".Debug();
            }

            // shutdown = false;

            return initializationSuccess;
        }

        private class DataboxApiController : WebApiController
        {
            [WebApiHandler(HttpVerbs.Get, "/*")]
            public bool Handle(WebServer server, HttpListenerContext context)
            {
                #region parameter check

                if (server == null)
                {
                    throw new ArgumentNullException(nameof(server));
                }

                if (context == null)
                {
                    throw new ArgumentNullException(nameof(context));
                }

                #endregion parameter check

                ($"Handling request '{context.Request.Url}' from remote endpoint '{context.Request.RemoteEndPoint}'.").Debug();

                string decodedRequest = HttpUtility.UrlDecode(context.Request.RawUrl);
                // string handleResult =  this.webrequestDispatcher.Handle(decodedRequest);

                context.Response.AddHeader("Access-Control-Allow-Origin", "*");
                return context.JsonResponse(new { Url = decodedRequest, Result = "OK" });
            }
        }
    }
}
```

**Comment by muus84** [comment]
Hi @mariodivece 

I will answer for Moonbird-IT. We are using VS2015 and .NETFramework Version v4.6. The build is compiled for x64 platform. Want do you else need?

**Comment by mariodivece** [comment]
maybe test the sample code I have provided and see if you can reproduce?

**Comment by DerKohnen** [comment]
Hi  @mariodivece 
I've been able to reproduce the exception with .NET Framework 4.6, 4.6.1 and 4.6.2. I used the sample code and added an FirstChanceExceptionHandler at start of Main:

```
AppDomain.CurrentDomain.FirstChanceException += (source, e) =>
            {
               Console.WriteLine($"{DateTime.Now:HH:mm:ss.fff} - FirstChanceException event raised in {AppDomain.CurrentDomain.FriendlyName} : { e.Exception}");
            };
```

Started the web server and sent one request. This is my console output:

```
11:44:18.782 - Finished Loading Web Server.
11:44:18.784 - Web server prefix 'http://localhost:9697/' added.
11:44:18.819 - Started HTTP Listener
11:44:19.322 - Initialization of WebServer succeeded.
11:44:55.260 - Start of Request 8fb0e97d - Source ::1:8080 - GET: /foobar
11:44:55.265 - Web API Module::WebApiModule.<.ctor>b__2_0
11:44:55.273 - Handler: Foo.Program+DataboxApiController.Handle
11:44:55.274 - Handling request 'http://localhost:9697/foobar' from remote endpoint '[::1]:8080'.
11:44:55.359 - Result: True
11:44:55.362 - End of Request 8fb0e97d
11:44:55.504 - Start of Request ce804b93 - Source ::1:8080 - GET: /favicon.ico
11:44:55.504 - Web API Module::WebApiModule.<.ctor>b__2_0
11:44:55.504 - Handling request 'http://localhost:9697/favicon.ico' from remote endpoint '[::1]:8080'.
11:44:55.504 - Handler: Foo.Program+DataboxApiController.Handle
11:44:55.531 - Result: True
11:44:55.532 - End of Request ce804b93
11:45:10.580 - FirstChanceException event raised in ConsoleApplication32.vshost.exe : System.ObjectDisposedException: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "System.Net.Sockets.Socket".
   bei System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
11:45:10.604 - FirstChanceException event raised in ConsoleApplication32.vshost.exe : System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "System.Net.Sockets.Socket".. ---> System.ObjectDisposedException: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "System.Net.Sockets.Socket".
   bei System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   bei System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   bei System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
11:45:10.629 - FirstChanceException event raised in ConsoleApplication32.vshost.exe : System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "System.Net.Sockets.Socket".. ---> System.ObjectDisposedException: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "System.Net.Sockets.Socket".
   bei System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   bei System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   bei System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   bei System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   bei System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
11:46:25.244 - FirstChanceException event raised in ConsoleApplication32.vshost.exe : System.ObjectDisposedException: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "System.Net.Sockets.Socket".
   bei System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
11:46:25.266 - FirstChanceException event raised in ConsoleApplication32.vshost.exe : System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "System.Net.Sockets.Socket".. ---> System.ObjectDisposedException: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "System.Net.Sockets.Socket".
   bei System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   bei System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   bei System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
11:46:25.287 - FirstChanceException event raised in ConsoleApplication32.vshost.exe : System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "System.Net.Sockets.Socket".. ---> System.ObjectDisposedException: Auf das verworfene Objekt kann nicht zugegriffen werden.
Objektname: "System.Net.Sockets.Socket".
   bei System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   bei System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   bei System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   bei System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   bei System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

**Comment by geoperez** [comment]
With the sample code I'm able to reproduce the issue.

**Comment by jpalcala** [comment]
I am not able to reproduce the error, the example provided by @DerKohnen works because the `FirstChanceException`  event is raised every time an exception is thrown but that doesn't mean the exception isn't  been caught. We'll keep this issue open for now in case someone has a code snippet that we can actually use to reproduce the error.
