### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by mgpreston** [unosquare/embedio#214]
Hello,

Thanks for the cool library! Is there any way to get it to listen on IPv6 addresses?

Using the `http://*:8080` form to listen on all addresses is hard-coded to use [`IPAddress.Any`](https://docs.microsoft.com/en-gb/dotnet/api/system.net.ipaddress.any), which only listens on IPv4 addresses. I'd need it to use [`IPAddress.IPv6Any`](https://docs.microsoft.com/en-gb/dotnet/api/system.net.ipaddress.ipv6any).

Using a URL prefix with the IPv6 "Any" form directly (`http://[::]:8080/`) and `HttpListenerMode.EmbedIO` results in an `ArgumentException` with message "Invalid port." from the WebServer constructor.

Stack trace:
```
   at Unosquare.Net.ListenerPrefix.CheckUri(String uri)
   at Unosquare.Net.HttpListenerPrefixCollection.Add(String uriPrefix)
   at Unosquare.Net.HttpListener.AddPrefix(String urlPrefix)
   at Unosquare.Labs.EmbedIO.WebServer..ctor(String[] urlPrefixes, RoutingStrategy routingStrategy, IHttpListener httpListener)
```

It seems the ListenerPrefix class doesn't support URIs with IPv6 addresses, as the colon character is considered the start of the port.

Kind regards,
Mark

**Comment by geoperez** [comment]
I like the idea. Let me take a look.

**Comment by geoperez** [comment]
Hello @mgpreston,

Can you check the PR #215 ?

You can setup IPv6 in two ways:

Using new `EndPointManager.UseIpv6` will set `IPAddress.IPv6Any` for `*` hostname:

```csharp
EndPointManager.UseIpv6 = true;
var instance = new WebServer("http://*:8877");
```

Or directly using the IPv6 address like the lookback:

```csharp
var instance = new WebServer("http://[::1]:8877");
```

**Comment by mgpreston** [comment]
Hi @geoperez,

This is great, and should be exactly what I was looking for! Many thanks for the getting this done so quickly!

**Comment by geoperez** [comment]
You can use the new nuget v2.1.0.

Let me know if I can close this issue.

**Comment by Unknown6656** [comment]
@geoperez Hello Sir.
Using the line
```csharp
EndPointManager.UseIpv6 = true;
```
the server will not be able to listen to IPv4 *and* IPv6. Is there a possible work-around (without creating two parallel servers)? Or is this a netsocket-restriction?

**Comment by geoperez** [comment]
Did you test it? I need to verify that because the value is set `IPAddress.IPv6Any` instead of  `IPAddress.Any` but I don't know if that value ignores ipv4.

**Comment by Unknown6656** [comment]
Yes I did test it. The server responds to `[::1]` but not to `127.0.0.1`.
It obviously responds to `localhost`, as this address will be resolved to `[::1]` and `127.0.0.1`.

**Comment by geoperez** [comment]
I'll add the option to bind IPv4 too when the flag UseIpv6 is set.

**Comment by Unknown6656** [comment]
Thank you very much, Sir.

... And I wanted to append my awe for your project. It is a wonderful library and absolutely fantastic!

**Comment by geoperez** [comment]
Please try using the following prerelease nuget:

https://www.nuget.org/packages/EmbedIO/2.2.0-pre1

**Comment by Unknown6656** [comment]
I have not been able to try the build `2.2.0-pre1`, as the server always throws an (internally catched) exception upon any incoming web request (without changing the code, which runs perfectly under `2.1.1`).
The exception is identical to the issue #118.

**Comment by geoperez** [comment]
Can you share your code?

**Comment by geoperez** [comment]
You are right, there is an issue with closing the connection properly that I introduced in the HTTPS support.

**Comment by Unknown6656** [comment]
~Well .... I could try to share the code, but it is an enormous codebase on my side and I am not quite sure which part could be the issue....~


> there is an issue with closing the connection properly that I introduced in the HTTPS support.

OK that may explain it..

**Comment by geoperez** [comment]
Hello @Unknown6656 , can you test with this version please?

https://www.nuget.org/packages/EmbedIO/2.2.0-pre2

**Comment by Unknown6656** [comment]
I have tested you package, however, I receive the same exceptions .....
I will try to create a secondary project later today in order to trace down the exact error source

**Comment by geoperez** [comment]
I released another version:

https://www.nuget.org/packages/EmbedIO/2.2.0-pre3

**Comment by Unknown6656** [comment]
Thank you, I do not get any exceptions anymore .... however, the exclusivity-issue concerning IPv4 and IPv6 still remains. By this I mean that I am only able to use *either* IPv4 or IPv6 -- but not both at the same time.
