### ISSUE TITLE
EmbedIO v3: Setting response ContentType causes error in log (but works)

### ISSUE THREAD

**Issue by rocketraman** [unosquare/embedio#322]
**Describe the bug**

Using EmbedIO v3 preview9.

When attempting to set the ContentType of a response, doing something like this:

```
Response.ContentType = "whatever";
...
await resultStream.CopyToAsync(Response.OutputStream);
return true;
```

the code seems to work, but a very scary looking Exception is printed to the logs:

```
00:08:18.104 ERR >> [WebServer] [9hunhKIZ5ke3S78nifWg6A] Unhandled exception.
    $type           : System.InvalidOperationException
    Message         : Cannot be changed after headers are sent.
    TargetSite      : Void set_ContentType(System.String)
    StackTrace      :
        at EmbedIO.Net.Internal.HttpListenerResponse.set_ContentType(String value)
        at EmbedIO.ResponseSerializer.<Json>d__1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at EmbedIO.WebApi.WebApiModuleBase.<SerializeResultAsync>d__25`1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at EmbedIO.Routing.RouteResolverBase`2.<ResolveAsync>d__8.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at EmbedIO.Routing.RouteResolverCollectionBase`3.<ResolveAsync>d__3.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at EmbedIO.Routing.RoutingModuleBase.<OnRequestAsync>d__2.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at EmbedIO.WebModuleBase.<HandleRequestAsync>d__15.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at EmbedIO.ExceptionHandler.<Handle>d__16.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at EmbedIO.WebModuleBase.<HandleRequestAsync>d__15.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at EmbedIO.Internal.WebModuleCollection.<DispatchRequestAsync>d__4.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
        at EmbedIO.WebServerBase`1.<DoHandleContextAsync>d__41.MoveNext()
    Source          : EmbedIO
    HResult         : -2146233079
 00:08:18.156 ERR >> [WebServer] [9hunhKIZ5ke3S78nifWg6A] Unhandled exception while handling exception.
    $type           : System.InvalidOperationException
    Message         : Cannot be changed after headers are sent.
    TargetSite      : Void set_StatusCode(Int32)
    StackTrace      :
        at EmbedIO.Net.Internal.HttpListenerResponse.set_StatusCode(Int32 value)
        at EmbedIO.HttpResponseExtensions.SetEmptyResponse(IHttpResponse this, Int32 statusCode)
        at EmbedIO.ExceptionHandler.<Handle>d__16.MoveNext()
    Source          : EmbedIO
    HResult         : -2146233079
```

**Comment by rdeago** [comment]
On second thought, if this happens in a web API controller method, you can just remove the `return true;` and change the method's return type to `void` (or `Task` if it is asynchronous).

**Comment by rocketraman** [comment]
Removing the `return true;` with a return type of `Task` fixed the problem. I'll note that all the documentation / samples for Embed/IO I found did have the `return true`...

**Comment by geoperez** [comment]
We need to update the documentation. We are working on that!

**Comment by geoperez** [comment]
We are starting the upgrade notes here: https://github.com/unosquare/embedio/wiki/Upgrade-from-v2
