### ISSUE TITLE
samples do not run

### ISSUE THREAD

**Issue by TomCJones** [unosquare/embedio#350]
**Describe the bug**
load embedio in vs2019 on windows ten
start Unosquare.Labs.EmdedIO.Samples

**Exception**
{"Method not found: 'System.String SQLitePCL.raw.sqlite3_errstr(Int32)'."}

   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Unosquare.Labs.LiteLib.LiteDbContext..ctor(String databaseFilePath, Boolean enabledLog)
   at Unosquare.Labs.EmbedIO.Samples.AppDbContext..ctor() in C:\Users\rp_to_000\Source\Repos\embedio\src\Unosquare.Labs.EmbedIO.Samples\AppDbContext.cs:line 7
   at Unosquare.Labs.EmbedIO.Samples.AppDbContext.InitDatabase() in C:\Users\rp_to_000\Source\Repos\embedio\src\Unosquare.Labs.EmbedIO.Samples\AppDbContext.cs:line 16
   at Unosquare.Labs.EmbedIO.Samples.Program.<Main>d__0.MoveNext() in C:\Users\rp_to_000\Source\Repos\embedio\src\Unosquare.Labs.EmbedIO.Samples\Program.cs:line 22

found this work around
https://github.com/fsprojects/Paket/issues/3632
I had the same issue, downgrading the versions of Microsoft.Data.Sqlite.core to 2.0.0 and SQlitePCLRaw.bundle_winsqlite3 to 1.1.8 fixed the error.

i went to SQlitePCLRaw.bundle_winsqlite3 to 1.1.8 and got this error error.
{"The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception."}	System.TypeInitializationException

   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Unosquare.Labs.LiteLib.LiteDbContext..ctor(String databaseFilePath, Boolean enabledLog)
   at Unosquare.Labs.EmbedIO.Samples.AppDbContext..ctor() in C:\Users\rp_to_000\Source\Repos\embedio\src\Unosquare.Labs.EmbedIO.Samples\AppDbContext.cs:line 7
   at Unosquare.Labs.EmbedIO.Samples.AppDbContext.InitDatabase() in C:\Users\rp_to_000\Source\Repos\embedio\src\Unosquare.Labs.EmbedIO.Samples\AppDbContext.cs:line 16
   at Unosquare.Labs.EmbedIO.Samples.Program.<Main>d__0.MoveNext() in C:\Users\rp_to_000\Source\Repos\embedio\src\Unosquare.Labs.EmbedIO.Samples\Program.cs:line 22

Could not downgrade Microsoft.Data.Sqlite.core to 2.0.0 because it was in LitLib and i did not want to recompile that

i did not understand this comment in AppCdContext : LiteDbContext
// map this context to the database file mydbfile.db and don't use any logging capabilities.

**Comment by rdeago** [comment]
On a side note, @geoperez, do we really need to use SQLite in the samples?

**Comment by geoperez** [comment]
The Litelib dependency (also Tubular) is a cross-selling, for showing more of the Open Sources projects from Unosquare. But let's clean-up the sample to keep it to the minimal dependencies.

I'll open a PR to resolve this issue.

**Comment by geoperez** [comment]
@TomCJones sorry for the delay. You can check the new sample without SQLite dependency!
