### ISSUE TITLE
The request connection was closed unexpectedly

### ISSUE THREAD

**Issue by geforce-hisa0904** [unosquare/embedio#413]
**Describe the bug**  
When EmbedIO Ver.3.1.3 running on .NET Framework 4.8 is accessed using HttpClient of .NET Framework 4.8, the following error occurs:

```c#
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Sample.Program.<RequestHttpAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Sample.Program.Main(String[] args)
```

**To Reproduce**  
Execute the following source code:

```c#
using EmbedIO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace Sample
{
    class Program
    {
        private const string DefaultUrl = "http://localhost:1234/";
        private const string Content = "content";

        static void Main(string[] args)
        {
            WebServer server = null;
            try
            {
                System.Globalization.CultureInfo.CurrentUICulture = new System.Globalization.CultureInfo("en-US");
                System.Globalization.CultureInfo.DefaultThreadCurrentUICulture = new System.Globalization.CultureInfo("en-US");

                server = CreateAndStartServer();
                RequestHttpAsync().GetAwaiter().GetResult();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            finally
            {
                server?.Dispose();
            }
        }
        private static WebServer CreateAndStartServer()
        {
            var server = new WebServer(HttpListenerMode.EmbedIO, DefaultUrl);
            server.WithAction("/", HttpVerbs.Any, async context =>
            {
                await context.SendDataAsync(context.Request.ContentLength64);
            });

            server.RunAsync();

            return server;
        }
        private static async Task RequestHttpAsync()
        {
            using (var client = new HttpClient())
            {
                var content = new StringContent(Content, Encoding.UTF8, "text/plain");
                using (var response = await client.PostAsync(DefaultUrl, content))
                {
                    var responseString = await response.Content.ReadAsStringAsync();
                    Console.WriteLine(responseString);
                }
            }
        }
    }
}
```

**Desktop (please complete the following information):**

- OS: Windows 10 Professional Version 1809 (OS build:17763.864)
- .NET Version: .NET Framework 4.8

**Additional context**  

Always occurs when run the unit test of [Issue389_RequestContentLength](https://github.com/unosquare/embedio/blob/bbbc8db07e0953370ffaf3545a8a1146bb686331/test/EmbedIO.Tests/Issues/Issue389_RequestContentLength.cs) using .NET Framework v.4.8.  
It seem that occurred the NullReferenceException.

**Comment by geoperez** [comment]
Hello, I'll take a look and let you know.

**Comment by geoperez** [comment]
According to the debugger, the null reference in `HttpConnection` is from the `_context.Listener`:

```
public ResponseStream GetResponseStream() => _oStream ??= new ResponseStream(Stream, _context.HttpListenerResponse, _context.Listener.IgnoreWriteExceptions);
```

**Comment by geoperez** [comment]
Can you check my PR? https://github.com/unosquare/embedio/pull/415

**Comment by geforce-hisa0904** [comment]
Thank you for creating PR. (It seems that is already merged to master..) I seem that is no problem.
I will close this ticket, but please process it correctly if there is a problem processing the ticket.
Thank you.

**Comment by geoperez** [comment]
I just pushed a new Nuget.
