### ISSUE TITLE
Exchange 2016 Database seeding failure. 

### ISSUE THREAD

**Issue by akprav** [unosquare/embedio#492]
I have tried update multiple time  and it is getting failed with below error, 

```
**Seeding to the local copy of database 'DAG16-Db017 ('e3f35cde-765c-4059-b2fd-7005709e39aa') failed: 
Msg=Seeding has been cancelled. Ex=Microsoft.Exchange.Cluster.Replay.SeederOperationAbortedException: The seeding operation failed. Error: Seeding has been cancelled. ---> Microsoft.Exchange.Cluster.Replay.NetworkCancelledException: Communication was cancelled. ---> System.IO.IOException: Unable to read data from the transport connection: Cannot access a disposed object.**
Object name: 'System.Net.Sockets.Socket'.. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.NegotiateStream.StartFrameBody(Int32 readBytes, Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.NegotiateStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.NegotiateStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.NegotiateStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Exchange.Cluster.Replay.TcpChannel.TryReadChunk(Byte[] buf, Int32 bufOffset, Int32 totalSize)
   at Microsoft.Exchange.Cluster.Replay.NetworkPackagingLayer.ReadData(Byte[] buf, Int32 off, Int32 len)
   at Microsoft.Exchange.Cluster.Replay.NetworkPackagingLayer.Read(Byte[] buf, Int32 off, Int32 len)
   at Microsoft.Exchange.Cluster.Replay.NetworkChannel.InvokeWithCatch(CatchableOperation op)
   --- End of inner exception stack trace ---
   at Microsoft.Exchange.Cluster.Replay.NetworkChannel.InvokeWithCatch(CatchableOperation op)
   at Microsoft.Exchange.Cluster.Replay.NetworkChannel.ReceiveFileInternal(NetworkChannelFileTransferReply reply, IReplicaSeederCallback callback, IPerfmonCounters copyPerfCtrs, CheckSummer summer, ISeedThrottle seedThrottle, FlushFileBuffersPerfData ffbPerfData)
   at Microsoft.Exchange.Cluster.Replay.NetworkChannel.ReceiveSeedingData(NetworkChannelFileTransferReply reply, IReplicaSeederCallback callback, ISeedThrottle seedThrottle, IPerfmonCounters perfCounters)
   at Microsoft.Exchange.Cluster.Replay.DatabaseSeederInstance.WriteDatabaseStreamToFile(NetworkChannelDatabaseRequest seedStartMessage, Guid databaseGuid, String databaseName, String sourceMachine, SeedPartitionInstance partition, SeedPartitionInstance mcdbPartition, UInt32 writeSize, Boolean fPrimaryPartitionSeedOnly, NetworkChannel channel, IReplicaSeederCallback callback, Action`1 deleteAction)
   at Microsoft.Exchange.Cluster.Replay.DatabaseSeederInstance.<>c__DisplayClass51_0.<SeedDatabasePartition>b__0()
   at Microsoft.Exchange.Cluster.Replay.FailoverPerformanceTrackerBase`1.RunTimedOperation(TOpCode opCode, Action operation)
   at Microsoft.Exchange.Cluster.Replay.DatabaseSeederInstance.SeedDatabasePartition(SeedPartitionInstance partition, Boolean enableThrottle, Boolean lowRedund, Boolean& isV3Protocol)
   at Microsoft.Exchange.Cluster.Replay.DatabaseSeederInstance.<>c__DisplayClass48_0.<SeedAllDatabasePartitions>b__1()
   at Microsoft.Exchange.Cluster.Replay.FailoverPerformanceTrackerBase`1.RunTimedOperation(TOpCode opCode, Action operation)
   at Microsoft.Exchange.Cluster.Replay.DatabaseSeederInstance.<SeedAllDatabasePartitions>b__48_0()
   at Microsoft.Exchange.Cluster.Replay.DatabaseSeederInstance.HandleSeedDatabasePartitionExceptions(SeedPartitionInstance partition, Action operation)
   --- End of inner exception stack trace (Microsoft.Exchange.Cluster.Replay.NetworkCancelledException) ---
   at Microsoft.Exchange.Cluster.Replay.SeederInstanceBase.LogError(Exception ex)
   at Microsoft.Exchange.Cluster.Replay.DatabaseSeederInstance.HandleSeedDatabasePartitionExceptions(SeedPartitionInstance partition, Action operation)
   at Microsoft.Exchange.Cluster.Replay.DatabaseSeederInstance.SeedThreadProcInternal()
   at Microsoft.Exchange.Data.Storage.Cluster.HaRpcExceptionWrapperBase`2.RunRpcServerOperation(String databaseName, RpcServerOperation rpcOperation)
   at Microsoft.Exchange.Cluster.Replay.SeederInstanceBase.LogError(Exception ex)
   at Microsoft.Exchange.Cluster.Replay.DatabaseSeederInstance.HandleSeedDatabasePartitionExceptions(SeedPartitionInstance partition, Action operation)
   at Microsoft.Exchange.Cluster.Replay.DatabaseSeederInstance.SeedThreadProcInternal()
   at Microsoft.Exchange.Data.Storage.Cluster.HaRpcExceptionWrapperBase`2.RunRpcServerOperation(String databaseName, RpcServerOperation 
```

**Comment by rdeago** [comment]
@akprav as much as I'd be glad to help you, I can't see how EmbedIO is involved here. Are you sure you didn't post on the wrong repository?

**Comment by akprav** [comment]
I'm new to Github, Appreciate if you can guide /map me to the correct forum.

**Comment by rdeago** [comment]
I'm not even sure GitHub is the right site. [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/) looks like a good starting point. Then again, I've never worked with Microsoft Exchange, let alone with clusters, so I've never needed to file an issue about it.

**Comment by rdeago** [comment]
@akprav did you find what you were looking for? May I be of further assistance, or can this ticket be closed?
